services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Aistea\Aisteablog\:
    resource: '../Classes/*'

  Aistea\Aisteablog\PageTitle\PostPageTitleProvider:
    tags:
      - name: 'pages.pageTitleProvider'
        priority: 50
        before: 'seo'
